stages:
  - test
  - report
  - pages

test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:10.0
  script:
    - dotnet restore
    - dotnet build --no-restore
    - dotnet test --no-build
        --logger "junit;LogFileName=TestResults.xml"
        --logger "trx;LogFileName=TestResults.trx"
        --results-directory ./test-results
  artifacts:
    when: always
    paths:
      - test-results/
    reports:
      junit: test-results/TestResults.xml

allure-report:
  stage: report
  image:
    name: frankescobar/allure-docker-service
    entrypoint: [""]
  dependencies:
    - test
  script:
    - allure generate test-results -o allure-report --clean
  artifacts:
    when: always
    paths:
      - allure-report/

pages:
  stage: pages
  dependencies:
    - allure-report
  script:
    - mv allure-report public
  artifacts:
    paths:
      - public
  only:
    - main
